services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nelsocated
      POSTGRES_PASSWORD: 120lago114
      POSTGRES_DB: walletbuddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
